name: gen

on:
  pull_request:
    branches: [ master ]

jobs:
  code:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Generate code
      # NOTE: Keep this container image as same as defined in Makefile
      uses: docker://ghcr.io/pipe-cd/codegen@sha256:0a2f9805e50f5c6efb7771171ddf291251bf349c2e8627fbf59c3535eacbbee0 # v0.53.0-10-g64742f7
      with:
        entrypoint: ./tool/codegen/codegen.sh
        args: /github/workspace
    - name: Show Git status
      shell: bash
      run: git status
    - name: Validate
      shell: bash
      run: test -z "$(git status --porcelain)"
